version: "3.8"

services:
  web:
    build: .
    command: ["python", "manage.py", "runserver", "0.0.0.0:8080"]
    ports:
      - 8001:8000
    working_dir: /usr/src/app/
    volumes:
      - ./:/usr/src/app/
    env_file:
      - ./.env

  db:
    image: mysql:5.7
    platform: linux/amd64  # MySQL 이미지의 플랫폼을 명시적으로 지정
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  app:
    depends_on:
      - db
    image: django
    volumes:
      - ./app_data:/var/www/html
    ports:
      - 8000:80
    restart: always
    environment:
      DJANGO_DB_HOSTS: db
      DJANGO_DB_NAME: ${DJANGO_DB_NAME}
      DJANGO_DB_USER: ${DJANGO_DB_USER}
      DJANGO_DB_PASSWORD: ${DJANGO_DB_PASSWORD}
